const WEATHER_CODES = {
  0: { label: "Clear sky", theme: "clear", stamp: "Clear" },
  1: { label: "Mainly clear", theme: "clear", stamp: "Bright" },
  2: { label: "Partly cloudy", theme: "cloudy", stamp: "Clouds" },
  3: { label: "Overcast", theme: "cloudy", stamp: "Overcast" },
  45: { label: "Fog", theme: "fog", stamp: "Fog" },
  48: { label: "Depositing rime fog", theme: "fog", stamp: "Fog" },
  51: { label: "Light drizzle", theme: "rain", stamp: "Drizzle" },
  53: { label: "Moderate drizzle", theme: "rain", stamp: "Drizzle" },
  55: { label: "Dense drizzle", theme: "rain", stamp: "Drizzle" },
  56: { label: "Light freezing drizzle", theme: "snow", stamp: "Icy" },
  57: { label: "Dense freezing drizzle", theme: "snow", stamp: "Icy" },
  61: { label: "Slight rain", theme: "rain", stamp: "Rain" },
  63: { label: "Moderate rain", theme: "rain", stamp: "Rain" },
  65: { label: "Heavy rain", theme: "rain", stamp: "Rain" },
  66: { label: "Light freezing rain", theme: "snow", stamp: "Icy" },
  67: { label: "Heavy freezing rain", theme: "snow", stamp: "Icy" },
  71: { label: "Slight snowfall", theme: "snow", stamp: "Snow" },
  73: { label: "Moderate snowfall", theme: "snow", stamp: "Snow" },
  75: { label: "Heavy snowfall", theme: "snow", stamp: "Snow" },
  77: { label: "Snow grains", theme: "snow", stamp: "Snow" },
  80: { label: "Slight rain showers", theme: "rain", stamp: "Showers" },
  81: { label: "Moderate rain showers", theme: "rain", stamp: "Showers" },
  82: { label: "Violent rain showers", theme: "storm", stamp: "Storm" },
  85: { label: "Slight snow showers", theme: "snow", stamp: "Snow" },
  86: { label: "Heavy snow showers", theme: "snow", stamp: "Snow" },
  95: { label: "Thunderstorm", theme: "storm", stamp: "Thunder" },
  96: { label: "Thunderstorm with hail", theme: "storm", stamp: "Thunder" },
  99: { label: "Strong thunderstorm with hail", theme: "storm", stamp: "Thunder" },
};

const elements = {
  body: document.body,
  cityInput: document.getElementById("cityInput"),
  searchForm: document.getElementById("searchForm"),
  searchButton: document.getElementById("searchButton"),
  geoButton: document.getElementById("geoButton"),
  searchResults: document.getElementById("searchResults"),
  heroTemp: document.getElementById("heroTemp"),
  heroCaption: document.getElementById("heroCaption"),
  locationName: document.getElementById("locationName"),
  locationMeta: document.getElementById("locationMeta"),
  conditionStamp: document.getElementById("conditionStamp"),
  currentTemp: document.getElementById("currentTemp"),
  conditionText: document.getElementById("conditionText"),
  updatedTime: document.getElementById("updatedTime"),
  todayRange: document.getElementById("todayRange"),
  feelsLikeText: document.getElementById("feelsLikeText"),
  humidityValue: document.getElementById("humidityValue"),
  windValue: document.getElementById("windValue"),
  precipitationValue: document.getElementById("precipitationValue"),
  pressureValue: document.getElementById("pressureValue"),
  sunriseValue: document.getElementById("sunriseValue"),
  sunsetValue: document.getElementById("sunsetValue"),
  forecastNarrative: document.getElementById("forecastNarrative"),
  hourlyGrid: document.getElementById("hourlyGrid"),
  dailyGrid: document.getElementById("dailyGrid"),
  toastContainer: document.getElementById("toastContainer"),
  unitToggle: document.getElementById("unitToggle"),
  recentSearches: document.getElementById("recentSearches"),
  loadingOverlay: document.getElementById("loadingOverlay"),
};

let isCelsius = true;
let currentWeatherData = null;

